# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: cdk 
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh

  # random utilities
  - name: utils
    before: |
      sudo apt-get install tree
#Link to install powershell on aws
#https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html

#Link to install powershell
#https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  - name: powershell
    before: |  
      ./bin/powershell_clid_install.sh

  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh

