#!/usr/bin/env bash

echo "== list objects"

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name. eg, ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME 


#list contents of the specific bucket
#aws s3 ls s3://bucket-name
#aws s3 ls s3://terraform-20240926145139957900000001

#download and print the content of the file in terminal:
#aws s3 cp s3://bucket-name/file_name - && cat -
#aws s3 cp s3://terraform-20240926145139957900000001/myfile.txt - && cat -