#!/usr/bin/env bash
echo "== list newest buckets"

#note: jq only accepts json format. you should have your aws output configured to be json

aws s3 ls
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'
echo "..."