#!/usr/bin/env bash

echo "== put-object"

#Exit immediately if any command returns a non-zero status
set -e

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name. eg, ./bucket my-bucket-name"
    exit 1
fi

# check for filename prefix 
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix. eg, ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY